ALTER TABLE events ADD COLUMN country_code VARCHAR(2) NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN city VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN lat FLOAT NOT NULL DEFAULT 0;
ALTER TABLE events ADD COLUMN lon FLOAT NOT NULL DEFAULT 0;

ALTER TABLE sessions ADD COLUMN country_code VARCHAR(2) NOT NULL DEFAULT '';
ALTER TABLE sessions ADD COLUMN city VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE sessions ADD COLUMN lat FLOAT NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN lon FLOAT NOT NULL DEFAULT 0;
